# Generated by Django 4.2.24 on 2025-09-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-hora_entrada'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AlterField(
            model_name='visita',
            name='hora_entrada',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automático al registrar la visita', verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='hora_salida',
            field=models.DateTimeField(blank=True, help_text='Timestamp de salida del visitante (opcional)', null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.TextField(help_text='Descripción del propósito de la visita', verbose_name='Motivo de la visita'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='nombre',
            field=models.CharField(help_text='Nombre y apellido del visitante', max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='rut',
            field=models.CharField(help_text='RUT chileno en formato 12345678-9', max_length=12, verbose_name='RUT'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['hora_entrada'], name='registro_vi_hora_en_d4684a_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['rut'], name='registro_vi_rut_0350d0_idx'),
        ),
    ]
