# Generated by Django 5.2.7 on 2025-10-31 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_visitas', '0002_alter_visita_options_alter_visita_hora_entrada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('en_curso', 'En curso'), ('completada', 'Completada')], default='en_curso', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='visita',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra'),
        ),
    ]
